name: Build and Package

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            TARGET: aarch64-apple-darwin

          - os: ubuntu-20.04
            TARGET: aarch64-unknown-linux-gnu

          - os: ubuntu-20.04
            TARGET: armv7-unknown-linux-gnueabihf

          - os: ubuntu-20.04
            TARGET: x86_64-unknown-linux-gnu

          - os: windows-latest
            TARGET: x86_64-pc-windows-msvc
            EXTENSION: .exe

          - os: windows-latest
            TARGET: i686-pc-windows-msvc
            EXTENSION: .exe

    steps:
      - name: Building ${{ matrix.TARGET }}
        run: echo "${{ matrix.TARGET }}"

      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22" # Substitua pela versão de Go que você deseja usar

      - name: Install dev dependencies
        if: contains(matrix.TARGET, 'linux')
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.0-dev

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      - name: Build the project
        if: contains(matrix.TARGET, 'windows')
        run: |
          go build -ldflags="-H windowsgui" -o app-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

      - name: Build
        if: ${{ !contains(matrix.TARGET, 'windows') }}
        run: |
          go build -o app-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

      - uses: actions/upload-artifact@master
        with:
          name: app-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
          path: app-${{ matrix.TARGET }}${{ matrix.EXTENSION }}

      - uses: svenstaro/upload-release-action@v2
        name: Upload binaries to release
        if: ${{ github.event_name == 'push' }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
          asset_name: app-${{ matrix.TARGET }}${{ matrix.EXTENSION }}
          tag: ${{ github.ref }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          overwrite: true
